# Generated by Django 5.1.3 on 2025-12-06 09:18

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="المعرف"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/icons/",
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/images/",
                        verbose_name="الصورة",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز"),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة العمولة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="stores.storecategory",
                        verbose_name="الفئة الأم",
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة المتاجر",
                "verbose_name_plural": "فئات المتاجر",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المتجر")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="المعرف"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="الوصف بالإنجليزية"),
                ),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "مطعم"),
                            ("grocery", "بقالة"),
                            ("supermarket", "سوبرماركت"),
                            ("pharmacy", "صيدلية"),
                            ("electronics", "إلكترونيات"),
                            ("fashion", "أزياء"),
                            ("home", "منزل وحديقة"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="نوع المتجر",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="stores/logos/%Y/%m/",
                        verbose_name="الشعار",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="stores/covers/%Y/%m/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="رقم الجوال"),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="رقم الواتساب"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="العنوان")),
                ("city", models.CharField(max_length=100, verbose_name="المدينة")),
                ("district", models.CharField(max_length=100, verbose_name="الحي")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="الموقع الجغرافي",
                    ),
                ),
                (
                    "delivery_radius_km",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="نطاق التوصيل (كم)",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="رسوم التوصيل",
                    ),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اتركه فارغاً إذا لم يكن هناك توصيل مجاني",
                        max_digits=10,
                        null=True,
                        verbose_name="حد التوصيل المجاني",
                    ),
                ),
                (
                    "estimated_delivery_time",
                    models.PositiveIntegerField(
                        default=30, verbose_name="وقت التوصيل المتوقع (دقيقة)"
                    ),
                ),
                (
                    "is_open_24h",
                    models.BooleanField(default=False, verbose_name="مفتوح 24 ساعة"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("active", "نشط"),
                            ("suspended", "موقوف"),
                            ("closed", "مغلق"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(default=True, verbose_name="مفتوح الآن"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="موثق"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="التقييم",
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد التقييمات"
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الطلبات"
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="إجمالي المبيعات",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اتركه فارغاً لاستخدام عمولة الفئة",
                        max_digits=5,
                        null=True,
                        verbose_name="نسبة العمولة",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المالك",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stores",
                        to="stores.storecategory",
                        verbose_name="الفئة",
                    ),
                ),
            ],
            options={
                "verbose_name": "متجر",
                "verbose_name_plural": "المتاجر",
                "ordering": ["-is_featured", "-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="StoreGallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="stores/gallery/%Y/%m/", verbose_name="الصورة"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="التعليق"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="stores.store",
                        verbose_name="المتجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة المتجر",
                "verbose_name_plural": "صور المتجر",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="StoreReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="التقييم",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="التعليق")),
                (
                    "food_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="تقييم الطعام",
                    ),
                ),
                (
                    "service_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="تقييم الخدمة",
                    ),
                ),
                (
                    "delivery_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="تقييم التوصيل",
                    ),
                ),
                (
                    "store_response",
                    models.TextField(blank=True, verbose_name="رد المتجر"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الرد"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="تقييم موثق"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="مرئي")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_reviews",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="stores.store",
                        verbose_name="المتجر",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم المتجر",
                "verbose_name_plural": "تقييمات المتاجر",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreWorkingHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "الأحد"),
                            (1, "الإثنين"),
                            (2, "الثلاثاء"),
                            (3, "الأربعاء"),
                            (4, "الخميس"),
                            (5, "الجمعة"),
                            (6, "السبت"),
                        ],
                        verbose_name="اليوم",
                    ),
                ),
                ("opening_time", models.TimeField(verbose_name="وقت الفتح")),
                ("closing_time", models.TimeField(verbose_name="وقت الإغلاق")),
                ("is_closed", models.BooleanField(default=False, verbose_name="مغلق")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="stores.store",
                        verbose_name="المتجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ساعات العمل",
                "verbose_name_plural": "ساعات العمل",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="stores.store",
                        verbose_name="المتجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "متجر مفضل",
                "verbose_name_plural": "المتاجر المفضلة",
                "ordering": ["-created_at"],
                "unique_together": {("user", "store")},
            },
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["status"], name="stores_stor_status_d56e36_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["category"], name="stores_stor_categor_21b6f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["city"], name="stores_stor_city_613ee7_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["is_featured"], name="stores_stor_is_feat_2fa04b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["rating"], name="stores_stor_rating_1f4b3d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="storereview",
            unique_together={("store", "user", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="storeworkinghours",
            unique_together={("store", "weekday")},
        ),
    ]
