# Generated by Django 5.1.3 on 2025-12-06 09:18

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المنطقة")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="الحدود الجغرافية",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "districts",
                    models.JSONField(blank=True, default=list, verbose_name="الأحياء"),
                ),
                (
                    "base_delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=10,
                        verbose_name="رسوم التوصيل الأساسية",
                    ),
                ),
                (
                    "per_km_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=10,
                        verbose_name="رسوم الكيلومتر",
                    ),
                ),
                (
                    "min_delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للتوصيل",
                    ),
                ),
                (
                    "max_delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=10,
                        verbose_name="الحد الأقصى للتوصيل",
                    ),
                ),
                (
                    "estimated_delivery_time",
                    models.PositiveIntegerField(
                        default=45, verbose_name="وقت التوصيل المتوقع (دقيقة)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="متاح للتوصيل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "منطقة التوصيل",
                "verbose_name_plural": "مناطق التوصيل",
            },
        ),
        migrations.CreateModel(
            name="DriverAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "الأحد"),
                            (1, "الإثنين"),
                            (2, "الثلاثاء"),
                            (3, "الأربعاء"),
                            (4, "الخميس"),
                            (5, "الجمعة"),
                            (6, "السبت"),
                        ],
                        verbose_name="اليوم",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="وقت البدء")),
                ("end_time", models.TimeField(verbose_name="وقت الانتهاء")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="متاح"),
                ),
            ],
            options={
                "verbose_name": "جدول توفر السائق",
                "verbose_name_plural": "جداول توفر السائقين",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="DriverLocationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="الموقع"
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="السرعة (كم/س)",
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الاتجاه",
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الدقة (متر)",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التسجيل"),
                ),
            ],
            options={
                "verbose_name": "موقع السائق",
                "verbose_name_plural": "مواقع السائقين",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAssignmentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "distance_to_pickup",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="المسافة للاستلام (كم)",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("sent", "تم الإرسال"),
                            ("accepted", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("timeout", "انتهت المهلة"),
                            ("cancelled", "ملغي"),
                        ],
                        default="sent",
                        max_length=20,
                        verbose_name="النتيجة",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الإرسال"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الرد"
                    ),
                ),
                (
                    "response_time",
                    models.PositiveIntegerField(
                        null=True, verbose_name="وقت الاستجابة (ثانية)"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="السائق",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل التعيين",
                "verbose_name_plural": "سجلات التعيين",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryEarnings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "earning_type",
                    models.CharField(
                        choices=[
                            ("delivery", "توصيل"),
                            ("tip", "بقشيش"),
                            ("bonus", "مكافأة"),
                            ("penalty", "خصم"),
                        ],
                        default="delivery",
                        max_length=20,
                        verbose_name="نوع الربح",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ"
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="الوصف")),
                (
                    "is_settled",
                    models.BooleanField(default=False, verbose_name="تمت التسوية"),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التسوية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_earnings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="السائق",
                    ),
                ),
            ],
            options={
                "verbose_name": "أرباح التوصيل",
                "verbose_name_plural": "أرباح التوصيل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "delivery_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="رقم التوصيل",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد البحث"),
                            ("assigned", "تم التعيين"),
                            ("accepted", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("picked_up", "تم الاستلام"),
                            ("in_transit", "في الطريق"),
                            ("delivered", "تم التوصيل"),
                            ("cancelled", "ملغي"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("pickup_address", models.TextField(verbose_name="عنوان الاستلام")),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="موقع الاستلام",
                    ),
                ),
                (
                    "pickup_contact_name",
                    models.CharField(
                        max_length=100, verbose_name="اسم التواصل للاستلام"
                    ),
                ),
                (
                    "pickup_contact_phone",
                    models.CharField(
                        max_length=15, verbose_name="رقم التواصل للاستلام"
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="عنوان التوصيل")),
                (
                    "delivery_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="موقع التوصيل",
                    ),
                ),
                (
                    "delivery_contact_name",
                    models.CharField(max_length=100, verbose_name="اسم العميل"),
                ),
                (
                    "delivery_contact_phone",
                    models.CharField(max_length=15, verbose_name="رقم العميل"),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="المسافة (كم)",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        null=True, verbose_name="الوقت المتوقع (دقيقة)"
                    ),
                ),
                (
                    "actual_duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الوقت الفعلي (دقيقة)"
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="رسوم التوصيل",
                    ),
                ),
                (
                    "driver_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="أرباح السائق",
                    ),
                ),
                (
                    "pickup_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الاستلام"),
                ),
                (
                    "delivery_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات التوصيل"),
                ),
                (
                    "driver_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات السائق"),
                ),
                (
                    "assignment_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="محاولات التعيين"
                    ),
                ),
                (
                    "delivery_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="delivery/proofs/%Y/%m/",
                        verbose_name="صورة التسليم",
                    ),
                ),
                (
                    "recipient_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="delivery/signatures/%Y/%m/",
                        verbose_name="توقيع المستلم",
                    ),
                ),
                (
                    "customer_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="تقييم العميل",
                    ),
                ),
                (
                    "customer_feedback",
                    models.TextField(blank=True, verbose_name="ملاحظات العميل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التعيين"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت القبول"
                    ),
                ),
                (
                    "picked_up_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الاستلام"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التوصيل"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإلغاء"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="السائق",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب توصيل",
                "verbose_name_plural": "طلبات التوصيل",
                "ordering": ["-created_at"],
            },
        ),
    ]
