# Generated by Django 5.1.3 on 2025-12-06 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrequest",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_request",
                to="orders.order",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="deliveryearnings",
            name="delivery_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="earnings",
                to="delivery.deliveryrequest",
                verbose_name="طلب التوصيل",
            ),
        ),
        migrations.AddField(
            model_name="deliveryassignmentlog",
            name="delivery_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_logs",
                to="delivery.deliveryrequest",
                verbose_name="طلب التوصيل",
            ),
        ),
        migrations.AddField(
            model_name="driveravailability",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_schedule",
                to=settings.AUTH_USER_MODEL,
                verbose_name="السائق",
            ),
        ),
        migrations.AddField(
            model_name="driverlocationhistory",
            name="delivery_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_history",
                to="delivery.deliveryrequest",
                verbose_name="طلب التوصيل",
            ),
        ),
        migrations.AddField(
            model_name="driverlocationhistory",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="السائق",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(fields=["status"], name="delivery_de_status_892df4_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(
                fields=["driver"], name="delivery_de_driver__4de6b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(
                fields=["created_at"], name="delivery_de_created_f37f02_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="driveravailability",
            unique_together={("driver", "weekday")},
        ),
        migrations.AddIndex(
            model_name="driverlocationhistory",
            index=models.Index(
                fields=["driver", "recorded_at"], name="delivery_dr_driver__c2179d_idx"
            ),
        ),
    ]
