# Generated by Django 5.1.3 on 2025-12-06 09:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="الاسم")),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[
                            ("moyasar", "ميسر"),
                            ("tap", "تاب"),
                            ("hyperpay", "هايبر باي"),
                            ("tabby", "تابي - تقسيط"),
                            ("tamara", "تمارا - تقسيط"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="نوع البوابة",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="مفتاح API")),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="المفتاح السري"
                    ),
                ),
                (
                    "publishable_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="المفتاح العام"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_sandbox",
                    models.BooleanField(default=True, verbose_name="وضع الاختبار"),
                ),
                (
                    "supports_mada",
                    models.BooleanField(default=True, verbose_name="يدعم مدى"),
                ),
                (
                    "supports_visa",
                    models.BooleanField(default=True, verbose_name="يدعم فيزا"),
                ),
                (
                    "supports_mastercard",
                    models.BooleanField(default=True, verbose_name="يدعم ماستركارد"),
                ),
                (
                    "supports_apple_pay",
                    models.BooleanField(default=False, verbose_name="يدعم Apple Pay"),
                ),
                (
                    "supports_installments",
                    models.BooleanField(default=False, verbose_name="يدعم التقسيط"),
                ),
                (
                    "transaction_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        max_digits=5,
                        verbose_name="نسبة الرسوم",
                    ),
                ),
                (
                    "transaction_fee_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        verbose_name="رسوم ثابتة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "بوابة الدفع",
                "verbose_name_plural": "بوابات الدفع",
            },
        ),
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم الخطة"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ الإجمالي"
                    ),
                ),
                (
                    "installments_count",
                    models.PositiveIntegerField(verbose_name="عدد الأقساط"),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قيمة القسط"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("completed", "مكتمل"),
                            ("defaulted", "متعثر"),
                            ("cancelled", "ملغي"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "paid_installments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الأقساط المدفوعة"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المبلغ المدفوع",
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateField(null=True, verbose_name="تاريخ القسط التالي"),
                ),
                (
                    "gateway_plan_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="رقم الخطة في البوابة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plans",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.paymentgateway",
                        verbose_name="مزود التقسيط",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطة تقسيط",
                "verbose_name_plural": "خطط التقسيط",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, verbose_name="رمز البطاقة")),
                (
                    "card_brand",
                    models.CharField(max_length=20, verbose_name="نوع البطاقة"),
                ),
                (
                    "card_last_four",
                    models.CharField(max_length=4, verbose_name="آخر 4 أرقام"),
                ),
                (
                    "card_holder_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم حامل البطاقة"
                    ),
                ),
                (
                    "expiry_month",
                    models.CharField(max_length=2, verbose_name="شهر الانتهاء"),
                ),
                (
                    "expiry_year",
                    models.CharField(max_length=4, verbose_name="سنة الانتهاء"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="البطاقة الافتراضية"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استخدام"
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cards",
                        to="payments.paymentgateway",
                        verbose_name="بوابة الدفع",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "بطاقة محفوظة",
                "verbose_name_plural": "البطاقات المحفوظة",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payout_id",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="رقم التحويل",
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ الإجمالي"
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="العمولة"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ الصافي"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=100, verbose_name="اسم البنك"),
                ),
                ("iban", models.CharField(max_length=34, verbose_name="رقم الآيبان")),
                (
                    "account_holder_name",
                    models.CharField(max_length=100, verbose_name="اسم صاحب الحساب"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("processing", "جاري التحويل"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="بداية الفترة")),
                ("period_end", models.DateField(verbose_name="نهاية الفترة")),
                (
                    "orders_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الطلبات"),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مرجع البنك"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التحويل"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="stores.store",
                        verbose_name="المتجر",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="التاجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحويل للتاجر",
                "verbose_name_plural": "تحويلات التجار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="رقم المعاملة",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "دفع"),
                            ("refund", "استرداد"),
                            ("payout", "تحويل للتاجر"),
                        ],
                        default="payment",
                        max_length=20,
                        verbose_name="نوع المعاملة",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mada", "مدى"),
                            ("visa", "فيزا"),
                            ("mastercard", "ماستركارد"),
                            ("apple_pay", "Apple Pay"),
                            ("wallet", "المحفظة"),
                            ("cash", "نقدي"),
                            ("installment", "تقسيط"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("processing", "جاري المعالجة"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                            ("cancelled", "ملغي"),
                            ("refunded", "مسترد"),
                            ("partially_refunded", "مسترد جزئياً"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الرسوم",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المبلغ الصافي",
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="رقم معاملة البوابة"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="استجابة البوابة"
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="نوع البطاقة"
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="آخر 4 أرقام"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رمز الخطأ"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المبلغ المسترد",
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت البدء"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الاكتمال"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="المتصفح")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.paymentgateway",
                        verbose_name="بوابة الدفع",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "original_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="payments.paymenttransaction",
                        verbose_name="المعاملة الأصلية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "معاملة دفع",
                "verbose_name_plural": "معاملات الدفع",
                "ordering": ["-initiated_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_id"], name="payments_pa_transac_c1fd68_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payments_pa_status_b6726a_idx"
                    ),
                    models.Index(
                        fields=["order"], name="payments_pa_order_i_d65105_idx"
                    ),
                    models.Index(
                        fields=["user"], name="payments_pa_user_id_3e3078_idx"
                    ),
                ],
            },
        ),
    ]
