# Generated by Django 5.1.3 on 2025-12-06 09:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المنتج")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, verbose_name="المعرف")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="الوصف بالإنجليزية"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رمز المنتج"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الباركود"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/images/%Y/%m/",
                        verbose_name="الصورة الرئيسية",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="السعر",
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="السعر الأصلي قبل الخصم",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="السعر قبل الخصم",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="للاستخدام الداخلي فقط",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="سعر التكلفة",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(default=True, verbose_name="خاضع للضريبة"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة الضريبة",
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(default=True, verbose_name="تتبع المخزون"),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الكمية المتوفرة"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=10, verbose_name="حد التنبيه للمخزون المنخفض"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="الوزن (كجم)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("active", "نشط"),
                            ("out_of_stock", "نفذ المخزون"),
                            ("discontinued", "متوقف"),
                        ],
                        default="active",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز"),
                ),
                (
                    "available_from",
                    models.TimeField(blank=True, null=True, verbose_name="متاح من"),
                ),
                (
                    "available_until",
                    models.TimeField(blank=True, null=True, verbose_name="متاح حتى"),
                ),
                (
                    "min_order_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="الحد الأدنى للطلب"
                    ),
                ),
                (
                    "max_order_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الحد الأقصى للطلب"
                    ),
                ),
                (
                    "preparation_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="وقت التحضير (دقيقة)"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="التقييم",
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد التقييمات"
                    ),
                ),
                (
                    "total_sold",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي المبيعات"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشاهدات"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="وصف SEO"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="stores.store",
                        verbose_name="المتجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAddon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="السعر",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="إلزامي"),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(default=5, verbose_name="الحد الأقصى"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "إضافة للمنتج",
                "verbose_name_plural": "إضافات المنتج",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductAddonGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المجموعة")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="إلزامي"),
                ),
                (
                    "min_selections",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الحد الأدنى للاختيار"
                    ),
                ),
                (
                    "max_selections",
                    models.PositiveIntegerField(
                        default=1, verbose_name="الحد الأقصى للاختيار"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addon_groups",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة الإضافات",
                "verbose_name_plural": "مجموعات الإضافات",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="AddonGroupItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="السعر الإضافي",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="الخيار الافتراضي"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.productaddongroup",
                        verbose_name="المجموعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر المجموعة",
                "verbose_name_plural": "عناصر المجموعة",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, verbose_name="المعرف")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/categories/%Y/%m/",
                        verbose_name="الصورة",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.productcategory",
                        verbose_name="الفئة الأم",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_categories",
                        to="stores.store",
                        verbose_name="المتجر",
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة المنتجات",
                "verbose_name_plural": "فئات المنتجات",
                "ordering": ["sort_order", "name"],
                "unique_together": {("store", "slug")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.productcategory",
                verbose_name="الفئة",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/%Y/%m/", verbose_name="الصورة"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="النص البديل"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة المنتج",
                "verbose_name_plural": "صور المنتج",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="التقييم",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="التعليق")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="مشتري موثق"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="مرئي")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم المنتج",
                "verbose_name_plural": "تقييمات المنتجات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رمز المنتج"
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="إضافة أو خصم من السعر الأساسي",
                        max_digits=10,
                        verbose_name="فرق السعر",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الكمية المتوفرة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "خيار المنتج",
                "verbose_name_plural": "خيارات المنتج",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="products.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج مفضل",
                "verbose_name_plural": "المنتجات المفضلة",
                "ordering": ["-created_at"],
                "unique_together": {("user", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["store", "status"], name="products_pr_store_i_ce0433_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_pr_price_9b1a5f_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured"], name="products_pr_is_feat_a5d7cd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("store", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "user")},
        ),
    ]
