# Generated by Django 5.1.3 on 2025-12-06 09:18

import django.contrib.gis.db.models.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="مفتاح الجلسة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سلة التسوق",
                "verbose_name_plural": "سلات التسوق",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "عنصر السلة",
                "verbose_name_plural": "عناصر السلة",
            },
        ),
        migrations.CreateModel(
            name="CartItemAddon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="الكمية"),
                ),
            ],
            options={
                "verbose_name": "إضافة لعنصر السلة",
                "verbose_name_plural": "إضافات عناصر السلة",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="الكود"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        max_length=15,
                        verbose_name="نوع الخصم",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="قيمة الخصم",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الحد الأقصى للخصم",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الحد الأقصى للاستخدام"
                    ),
                ),
                (
                    "max_uses_per_user",
                    models.PositiveIntegerField(
                        default=1, verbose_name="الحد الأقصى لكل مستخدم"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد مرات الاستخدام"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("valid_from", models.DateTimeField(verbose_name="صالح من")),
                ("valid_until", models.DateTimeField(verbose_name="صالح حتى")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "كوبون",
                "verbose_name_plural": "الكوبونات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="رقم الطلب",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("confirmed", "تم التأكيد"),
                            ("preparing", "جاري التحضير"),
                            ("ready", "جاهز للاستلام"),
                            ("picked_up", "تم الاستلام من المتجر"),
                            ("on_the_way", "في الطريق"),
                            ("delivered", "تم التوصيل"),
                            ("cancelled", "ملغي"),
                            ("refunded", "مسترد"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الطلب",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("paid", "مدفوع"),
                            ("failed", "فشل"),
                            ("refunded", "مسترد"),
                            ("partially_refunded", "مسترد جزئياً"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الدفع",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "الدفع عند الاستلام"),
                            ("card", "بطاقة ائتمان"),
                            ("mada", "مدى"),
                            ("apple_pay", "Apple Pay"),
                            ("wallet", "المحفظة"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("delivery", "توصيل"), ("pickup", "استلام من المتجر")],
                        default="delivery",
                        max_length=15,
                        verbose_name="نوع التوصيل",
                    ),
                ),
                (
                    "delivery_address_text",
                    models.TextField(blank=True, verbose_name="نص العنوان"),
                ),
                (
                    "delivery_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="موقع التوصيل",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="المجموع الفرعي",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="رسوم التوصيل",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="قيمة الخصم",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الضريبة",
                    ),
                ),
                (
                    "tip_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="البقشيش",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الإجمالي",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات العميل"),
                ),
                (
                    "store_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات المتجر"),
                ),
                (
                    "driver_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات السائق"),
                ),
                (
                    "estimated_preparation_time",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="وقت التحضير المتوقع (دقيقة)",
                    ),
                ),
                (
                    "estimated_delivery_time",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="وقت التوصيل المتوقع (دقيقة)",
                    ),
                ),
                (
                    "placed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الطلب"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التأكيد"
                    ),
                ),
                (
                    "preparing_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت بدء التحضير"
                    ),
                ),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الجاهزية"
                    ),
                ),
                (
                    "picked_up_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الاستلام من المتجر"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التوصيل"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإلغاء"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                (
                    "is_rated",
                    models.BooleanField(default=False, verbose_name="تم التقييم"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="اسم المنتج"),
                ),
                (
                    "product_name_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="اسم المنتج بالإنجليزية",
                    ),
                ),
                (
                    "variant_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم الخيار"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "addons_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مجموع الإضافات",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "عنصر الطلب",
                "verbose_name_plural": "عناصر الطلب",
            },
        ),
        migrations.CreateModel(
            name="OrderItemAddon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "addon_name",
                    models.CharField(max_length=100, verbose_name="اسم الإضافة"),
                ),
                (
                    "addon_name_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="اسم الإضافة بالإنجليزية",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="الكمية"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر"
                    ),
                ),
            ],
            options={
                "verbose_name": "إضافة لعنصر الطلب",
                "verbose_name_plural": "إضافات عناصر الطلب",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="الحالة")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
            ],
            options={
                "verbose_name": "سجل حالة الطلب",
                "verbose_name_plural": "سجل حالات الطلبات",
                "ordering": ["-created_at"],
            },
        ),
    ]
