# Generated by Django 5.1.3 on 2025-12-06 09:18

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="رقم الجوال السعودي",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الجوال يجب أن يكون سعودي صالح (مثال: 0512345678)",
                                regex="^(\\+966|966|0)?5[0-9]{8}$",
                            )
                        ],
                        verbose_name="رقم الجوال",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="الاسم الأول"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="اسم العائلة"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("customer", "عميل"),
                            ("vendor", "تاجر"),
                            ("driver", "سائق"),
                            ("admin", "مدير"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="نوع المستخدم",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="تم التحقق من رقم الجوال",
                        verbose_name="تم التحقق",
                    ),
                ),
                (
                    "is_identity_verified",
                    models.BooleanField(
                        default=False,
                        help_text="تم التحقق من الهوية الوطنية",
                        verbose_name="تم التحقق من الهوية",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الهوية يجب أن يكون 10 أرقام ويبدأ بـ 1 أو 2",
                                regex="^[12][0-9]{9}$",
                            )
                        ],
                        verbose_name="رقم الهوية",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("is_staff", models.BooleanField(default=False, verbose_name="موظف")),
                (
                    "wallet_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="رصيد المحفظة",
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        unique=True,
                        verbose_name="كود الإحالة",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English")],
                        default="ar",
                        max_length=5,
                        verbose_name="اللغة",
                    ),
                ),
                (
                    "push_notifications_enabled",
                    models.BooleanField(default=True, verbose_name="تفعيل الإشعارات"),
                ),
                (
                    "sms_notifications_enabled",
                    models.BooleanField(default=True, verbose_name="تفعيل رسائل SMS"),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        blank=True,
                        help_text="Firebase Cloud Messaging token",
                        verbose_name="رمز FCM",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تسجيل دخول"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تمت إحالته بواسطة",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمين",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="مثال: المنزل، العمل",
                        max_length=50,
                        verbose_name="العنوان المختصر",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "المنزل"),
                            ("work", "العمل"),
                            ("other", "أخرى"),
                        ],
                        default="home",
                        max_length=10,
                        verbose_name="نوع العنوان",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(max_length=255, verbose_name="العنوان"),
                ),
                (
                    "building_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم المبنى"
                    ),
                ),
                (
                    "apartment_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الشقة"
                    ),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="الطابق"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="المدينة")),
                ("district", models.CharField(max_length=100, verbose_name="الحي")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="الرمز البريدي"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="إحداثيات GPS",
                        null=True,
                        srid=4326,
                        verbose_name="الموقع الجغرافي",
                    ),
                ),
                (
                    "additional_directions",
                    models.TextField(
                        blank=True,
                        help_text="مثال: بجوار مسجد النور",
                        verbose_name="توجيهات إضافية",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الجوال يجب أن يكون سعودي صالح (مثال: 0512345678)",
                                regex="^(\\+966|966|0)?5[0-9]{8}$",
                            )
                        ],
                        verbose_name="رقم التواصل",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="العنوان الافتراضي"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنوان",
                "verbose_name_plural": "العناوين",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("suspended", "موقوف"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_online", models.BooleanField(default=False, verbose_name="متصل")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="متاح للطلبات"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "دراجة نارية"),
                            ("car", "سيارة"),
                            ("van", "فان"),
                            ("truck", "شاحنة"),
                        ],
                        max_length=15,
                        verbose_name="نوع المركبة",
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(max_length=100, verbose_name="موديل المركبة"),
                ),
                (
                    "vehicle_year",
                    models.PositiveSmallIntegerField(verbose_name="سنة الصنع"),
                ),
                (
                    "vehicle_color",
                    models.CharField(max_length=50, verbose_name="لون المركبة"),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم اللوحة"
                    ),
                ),
                (
                    "driving_license",
                    models.ImageField(
                        upload_to="drivers/licenses/%Y/%m/", verbose_name="رخصة القيادة"
                    ),
                ),
                (
                    "vehicle_registration",
                    models.ImageField(
                        upload_to="drivers/registrations/%Y/%m/",
                        verbose_name="استمارة المركبة",
                    ),
                ),
                (
                    "vehicle_insurance",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="drivers/insurance/%Y/%m/",
                        verbose_name="تأمين المركبة",
                    ),
                ),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="الموقع الحالي",
                    ),
                ),
                (
                    "last_location_update",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تحديث للموقع"
                    ),
                ),
                (
                    "total_deliveries",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي التوصيلات"
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="إجمالي الأرباح",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="التقييم",
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد التقييمات"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف السائق",
                "verbose_name_plural": "ملفات السائقين",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="رقم الجوال يجب أن يكون سعودي صالح (مثال: 0512345678)",
                                regex="^(\\+966|966|0)?5[0-9]{8}$",
                            )
                        ],
                        verbose_name="رقم الجوال",
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="الرمز")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "تسجيل جديد"),
                            ("login", "تسجيل دخول"),
                            ("password_reset", "إعادة تعيين كلمة المرور"),
                            ("phone_change", "تغيير رقم الجوال"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="الغرض",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="عدد المحاولات"
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="مستخدم")),
                ("expires_at", models.DateTimeField(verbose_name="تاريخ الانتهاء")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "رمز التحقق",
                "verbose_name_plural": "رموز التحقق",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "purpose"],
                        name="accounts_ot_phone_n_3b8ec0_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_ot_expires_57ad4f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=200, verbose_name="اسم النشاط التجاري"),
                ),
                (
                    "business_name_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="اسم النشاط بالإنجليزية",
                    ),
                ),
                (
                    "commercial_registration",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="السجل التجاري"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="الرقم الضريبي"
                    ),
                ),
                (
                    "commercial_registration_doc",
                    models.FileField(
                        upload_to="vendors/docs/%Y/%m/",
                        verbose_name="وثيقة السجل التجاري",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم البنك"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="رقم الآيبان"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("suspended", "موقوف"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة العمولة",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="إجمالي المبيعات",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الطلبات"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف التاجر",
                "verbose_name_plural": "ملفات التجار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "إيداع"), ("debit", "سحب")],
                        max_length=10,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                            ("refunded", "مسترد"),
                        ],
                        default="completed",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="الوصف"),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم المرجع"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الرصيد بعد العملية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ العملية"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية محفظة",
                "verbose_name_plural": "عمليات المحفظة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="accounts_us_phone_n_613c4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="accounts_us_user_ty_b6cfc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["referral_code"], name="accounts_us_referra_2cbfb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_4734df_idx"
            ),
        ),
    ]
