# Generated by Django 5.1.3 on 2025-12-06 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("order_placed", "طلب جديد"),
                            ("order_confirmed", "تأكيد الطلب"),
                            ("order_preparing", "جاري التحضير"),
                            ("order_ready", "الطلب جاهز"),
                            ("order_on_way", "في الطريق"),
                            ("order_delivered", "تم التوصيل"),
                            ("order_cancelled", "إلغاء الطلب"),
                            ("payment_success", "نجاح الدفع"),
                            ("payment_failed", "فشل الدفع"),
                            ("refund_processed", "تم الاسترداد"),
                            ("promo_code", "كود خصم"),
                            ("new_store", "متجر جديد"),
                            ("review_reminder", "تذكير بالتقييم"),
                            ("wallet_credit", "إضافة للمحفظة"),
                            ("driver_assigned", "تعيين السائق"),
                            ("general", "عام"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="نوع القالب",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="العنوان بالعربية"),
                ),
                ("body_ar", models.TextField(verbose_name="المحتوى بالعربية")),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, verbose_name="العنوان بالإنجليزية"
                    ),
                ),
                ("body_en", models.TextField(verbose_name="المحتوى بالإنجليزية")),
                (
                    "is_push_enabled",
                    models.BooleanField(default=True, verbose_name="إشعار فوري"),
                ),
                (
                    "is_sms_enabled",
                    models.BooleanField(default=False, verbose_name="رسالة SMS"),
                ),
                (
                    "is_email_enabled",
                    models.BooleanField(default=False, verbose_name="بريد إلكتروني"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الأيقونة"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="رابط الإجراء"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قالب إشعار",
                "verbose_name_plural": "قوالب الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="الموضوع")),
                ("body_html", models.TextField(verbose_name="المحتوى HTML")),
                (
                    "body_text",
                    models.TextField(blank=True, verbose_name="المحتوى النصي"),
                ),
                (
                    "email_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نوع البريد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("sent", "تم الإرسال"),
                            ("delivered", "تم التسليم"),
                            ("opened", "تم الفتح"),
                            ("clicked", "تم النقر"),
                            ("bounced", "مرتجع"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="معرف الرسالة"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الفتح"
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت النقر"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل بريد",
                "verbose_name_plural": "سجلات البريد",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(verbose_name="المحتوى")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order", "طلب"),
                            ("payment", "دفع"),
                            ("promo", "عرض"),
                            ("system", "نظام"),
                            ("chat", "محادثة"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نوع المرجع"
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(blank=True, null=True, verbose_name="معرف المرجع"),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="صورة")),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="رابط الإجراء"
                    ),
                ),
                (
                    "action_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات الإجراء"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت القراءة"
                    ),
                ),
                (
                    "push_sent",
                    models.BooleanField(default=False, verbose_name="تم إرسال Push"),
                ),
                (
                    "push_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت إرسال Push"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "push_orders",
                    models.BooleanField(default=True, verbose_name="إشعارات الطلبات"),
                ),
                (
                    "push_promotions",
                    models.BooleanField(default=True, verbose_name="العروض والخصومات"),
                ),
                (
                    "push_news",
                    models.BooleanField(
                        default=True, verbose_name="الأخبار والتحديثات"
                    ),
                ),
                (
                    "push_chat",
                    models.BooleanField(default=True, verbose_name="رسائل المحادثة"),
                ),
                (
                    "sms_orders",
                    models.BooleanField(default=True, verbose_name="رسائل الطلبات"),
                ),
                (
                    "sms_otp",
                    models.BooleanField(default=True, verbose_name="رسائل OTP"),
                ),
                (
                    "sms_promotions",
                    models.BooleanField(default=False, verbose_name="رسائل العروض"),
                ),
                (
                    "email_orders",
                    models.BooleanField(default=True, verbose_name="بريد الطلبات"),
                ),
                (
                    "email_promotions",
                    models.BooleanField(default=False, verbose_name="بريد العروض"),
                ),
                (
                    "email_newsletter",
                    models.BooleanField(default=False, verbose_name="النشرة البريدية"),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(default=False, verbose_name="ساعات الهدوء"),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="بداية الهدوء"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="نهاية الهدوء"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفضيلات الإشعارات",
                "verbose_name_plural": "تفضيلات الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="PushLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fcm_token", models.TextField(verbose_name="رمز FCM")),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("body", models.TextField(verbose_name="المحتوى")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="البيانات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("sent", "تم الإرسال"),
                            ("delivered", "تم التسليم"),
                            ("opened", "تم الفتح"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "fcm_message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="معرف FCM"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الفتح"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="push_logs",
                        to="notifications.notification",
                        verbose_name="الإشعار",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل Push",
                "verbose_name_plural": "سجلات Push",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="رقم الجوال"),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "message_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نوع الرسالة"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("unifonic", "يونيفونك"),
                            ("msegat", "مسجات"),
                            ("twilio", "تويليو"),
                        ],
                        default="unifonic",
                        max_length=20,
                        verbose_name="المزود",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("sent", "تم الإرسال"),
                            ("delivered", "تم التسليم"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="معرف الرسالة"
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="استجابة المزود"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=6,
                        verbose_name="التكلفة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإرسال"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت التسليم"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل SMS",
                "verbose_name_plural": "سجلات SMS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "notification_type"],
                name="notificatio_user_id_f77590_idx",
            ),
        ),
    ]
